// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CheckCppHeader
{
    internal sealed partial class Vsix
    {
        public const string Id = "CheckCppHeader.1d193db7-9a85-481d-acf0-586a52c3da57";
        public const string Name = "CheckCppHeader";
        public const string Description = @"CheckCppHeader";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Dexter Zou";
        public const string Tags = "";
    }
}
